version: '3.7'
services:
    mysql-db:
        container_name: avkdb
        image: mysql:5.7
        build:
            context: ./database
            dockerfile: Dockerfile
        expose: 
            - "3306"
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=avk
        volumes:
            - $PWD/database/mysql-5.7/:/var/lib/mysql
        networks:
            - avk-net
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST="avkdb"
            - PMA_PORT="3307"
        depends_on:
            - mysql-db
        ports:
            - 8080:80
        links: 
            - mysql-db
        volumes:
            - $PWD/database/phpmyadmin/:/etc/phpmyadmin
        networks:
            - avk-net
    adminer:
        image: adminer
        container_name: adminer
        ports:
            - 8000:8080
        environment:
            - ADMINER_DEFAULT_SERVER="avkdb"
            - ADMINER_DESIGN=nette
        links:
            - mysql-db
networks:
    avk-net:
        


