version: '3'
services:
    mysql-db:
        container_name: avkdb
        image: mysql:5.7
        build:
            context: ./database
            dockerfile: Dockerfile
        ports:
            - "3307:3306"
        volumes:
            - $PWD/database/mysql-5.7/:/var/lib/mysql
        networks:
            - avk-net
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql-db
        depends_on:
            - mysql-db
        ports:
            - 8080:80
        volumes:
            - $PWD/database/phpmyadmin/:/etc/phpmyadmin
        networks:
            - avk-net
networks:
    avk-net: